import test from 'node:test';
import assert from 'node:assert/strict';
import {createDB} from '../server/local.mjs';
import {handleApi,flushOutbox} from '../server/api.mjs';
import {quoteBooking,pricingSettings,taxTotals,validateBooking,localParts,SERVICES} from '../shared/catalog.mjs';
const now=new Date('2026-09-07T15:00:00Z'); // 11:00 Toronto
const base={serviceId:'affidavits',operation:'commissioning',date:'2026-09-07',time:'15:00',mode:'online',platform:'zoom',quantity:1,hours:1,address:'',name:'Test Customer',email:'customer@example.test',phone:'4165550100',notes:'',termsAccepted:true,termsVersion:'p1-review'};
function context(){const messages=[];const env={DB:createDB(),NOW:()=>now,BOOKING_SECRET:'test-secret-'.repeat(5),ADMIN_TOKEN:'test-owner-'.repeat(5),RESEND_API_KEY:'test-only',BOOKING_FROM_EMAIL:'sender@example.test',BOOKING_OWNER_EMAIL:'owner@example.test',ETRANSFER_EMAIL:'transfer@example.test',MAIL_FETCH:async(_url,options)=>{messages.push(JSON.parse(options.body));return new Response(JSON.stringify({id:'test'}),{status:200});}};return {env,messages};}
async function call(env,path,method='GET',data,headers={}){const res=await handleApi(new Request('https://example.test'+path,{method,headers:{'Content-Type':'application/json',...headers},...(data?{body:JSON.stringify(data)}:{})}),env);return {status:res.status,data:await res.json()};}
const inquiry={business:'Example Co',name:'Test Owner',email:'example@example.test',phone:'4165550100',notarizations:'20',commissions:'10',contactMethod:'email',notes:'Please discuss options'};
async function submit(env,values=inquiry,key=crypto.randomUUID()){return call(env,'/api/inquiry','POST',values,{'Idempotency-Key':key});}
const adminHeaders=env=>({Authorization:`Bearer ${env.ADMIN_TOKEN}`});
test('six categories retain four original image sources and grouped drafting',()=>{assert.equal(SERVICES.length,6);assert.deepEqual(SERVICES.slice(3).map(x=>x.id),['international','mediation','drafting']);assert.deepEqual(SERVICES[5].operations,['draft-affidavit','draft-consent']);assert.match(SERVICES[0].image,/1057613520/);assert.match(SERVICES[3].image,/1545239351/);});
test('money math uses integer cents and complementary rounding',()=>{assert.deepEqual(taxTotals(6500),{subtotal:6500,tax:845,total:7345,deposit:3673,balance:3672,currency:'CAD'});for(const amount of [1,50,100,11500,999999]){const q=taxTotals(amount);assert.equal(q.deposit+q.balance,q.total);}assert.throws(()=>taxTotals(NaN));});
test('mediation and drafting prices, tax and deposit',()=>{const m=quoteBooking({...base,serviceId:'mediation',operation:'mediation',hours:2});assert.equal(m.total,22600);assert.equal(m.deposit,11300);const d=quoteBooking({...base,serviceId:'drafting',operation:'draft-consent'});assert.equal(d.total,5650);assert.equal(d.deposit,2825);});
test('existing seal rates and urgent multiplier are not mixed with page pricing',()=>{assert.equal(quoteBooking({...base,quantity:2}).subtotal,4400);assert.equal(quoteBooking({...base,quantity:2,time:'18:00'}).subtotal,8800);assert.equal(quoteBooking({...base,serviceId:'copies',operation:'notarization',quantity:2}).subtotal,5400);});
test('bulk boundary pricing is activated only for configured operations',()=>{const config=pricingSettings({PAGE_PRICING_OPERATIONS:'commissioning'});for(const [n,amount]of [[1,1500],[14,21000],[15,6000],[49,19600],[50,15000]])assert.equal(quoteBooking({...base,quantity:n},config).subtotal,amount);assert.equal(quoteBooking({...base,quantity:15}).subtotal,23900);});
test('unknown travel and unresolved urgent scope never generate a complete payable total',()=>{assert.equal(quoteBooking({...base,mode:'mobile'}).status,'review_required');assert.equal(quoteBooking({...base,serviceId:'mediation',operation:'mediation',time:'18:00'}).status,'review_required');});
test('Toronto day, 18:00 and 30-minute boundaries',()=>{assert.equal(localParts(new Date('2026-09-08T02:00:00Z')).date,'2026-09-07');assert.ok(validateBooking({...base,time:'18:00'},new Date('2026-09-07T21:31:00Z')).errors.time);assert.equal(validateBooking({...base,time:'18:00'},new Date('2026-09-07T21:30:00Z')).errors.time,undefined);assert.ok(validateBooking({...base,time:'18:00',mode:'mobile'},now).errors.mode);assert.ok(validateBooking({...base,date:'2026-09-08'},now).errors.date);assert.ok(validateBooking({...base,time:'25:00'},now).errors.time);});
test('urgent Zoom and WhatsApp require phone; physical notarization cannot be online',()=>{assert.ok(validateBooking({...base,time:'18:00',phone:''},now).errors.phone);assert.ok(validateBooking({...base,platform:'whatsapp',phone:''},now).errors.phone);assert.ok(validateBooking({...base,serviceId:'business',operation:'notarization'},now).errors.operation);assert.ok(validateBooking({...base,quantity:0},now).errors.quantity);});
test('missing email settings fails honestly without recording a request',async()=>{const {env}=context();env.RESEND_API_KEY='';const r=await submit(env);assert.equal(r.status,503);assert.equal(env.DB.sqlite.prepare('SELECT COUNT(*) AS n FROM requests').get().n,0);});
test('duplicate submission uses one durable request and does not resend',async()=>{const {env,messages}=context();const key=crypto.randomUUID();const a=await submit(env,inquiry,key);const b=await submit(env,inquiry,key);assert.equal(a.data.id,b.data.id);assert.equal(env.DB.sqlite.prepare('SELECT COUNT(*) AS n FROM requests').get().n,1);assert.equal(messages.length,1);const conflict=await submit(env,{...inquiry,name:'Different Customer'},key);assert.equal(conflict.status,409);});
test('email failures stay pending and are retried without rebooking',async()=>{const {env}=context();env.MAIL_FETCH=async()=>new Response('',{status:503});const a=await submit(env);assert.equal(a.status,201);assert.equal(a.data.emailStatus,'pending');env.MAIL_FETCH=async()=>new Response('{}',{status:200});await flushOutbox(env);assert.equal(env.DB.sqlite.prepare('SELECT email_status FROM requests').get().email_status,'sent');});
test('business inquiry is separate from checkout and includes required volumes',async()=>{const {env,messages}=context();const r=await call(env,'/api/inquiry','POST',{business:'Example Co',name:'Test Owner',email:'example@example.test',phone:'4165550100',notarizations:'20',commissions:'10',contactMethod:'email',notes:'Please discuss options'},{'Idempotency-Key':crypto.randomUUID()});assert.equal(r.status,201);assert.match(messages[0].subject,/business subscription/);assert.match(messages[0].text,/Monthly notarizations: 20/);});

test('request transaction rolls back when owner notification cannot be queued',async()=>{const {env}=context();env.DB.sqlite.exec("CREATE TRIGGER fail_request BEFORE INSERT ON outbox BEGIN SELECT RAISE(ABORT,'test failure'); END;");assert.equal((await submit(env)).status,400);assert.equal(env.DB.sqlite.prepare('SELECT COUNT(*) AS n FROM requests').get().n,0);});

test('separate production environment retains its owner notification recipient',async()=>{const {env,messages}=context();env.BOOKING_OWNER_EMAIL='admin@on-callnotary.ca';assert.equal((await submit(env)).status,201);assert.deepEqual(messages[0].to,['admin@on-callnotary.ca']);});

test('retired booking endpoints cannot mutate saved data',async()=>{const {env,messages}=context();for(const [path,method] of [['/api/config','GET'],['/api/quote','POST'],['/api/booking','POST'],['/api/booking/P1-abcd','GET'],['/api/admin/P1-abcd/confirm','POST'],['/api/admin/P1-abcd/received','POST']])assert.equal((await call(env,path,method,method==='POST'?{}:undefined)).status,410);assert.equal(env.DB.sqlite.prepare('SELECT COUNT(*) n FROM requests').get().n,0);assert.equal(messages.length,0);});
test('owner access and cross-origin inquiry submissions remain protected',async()=>{const {env}=context();assert.equal((await call(env,'/api/admin/requests')).status,401);assert.equal((await call(env,'/api/admin/retry-email','POST',{})).status,401);assert.equal((await call(env,'/api/inquiry','POST',inquiry,{Origin:'https://attacker.test'})).status,403);assert.equal((await call(env,'/api/admin/requests','GET',undefined,adminHeaders(env))).status,200);});
test('email retry leaves legacy booking jobs and records untouched',async()=>{const {env,messages}=context();env.DB.sqlite.prepare('INSERT INTO requests (id,access_hash,idempotency_key,input_hash,kind,payload,created_at) VALUES (?,?,?,?,?,?,?)').run('P1-legacy','hash','legacy-key','hash','booking','{}',new Date().toISOString());env.DB.sqlite.prepare('INSERT INTO outbox (id,request_id,recipient,subject,body,created_at) VALUES (?,?,?,?,?,?)').run('legacy-job','P1-legacy','old@example.test','Old booking','Do not send',new Date().toISOString());await submit(env);await flushOutbox(env);assert.equal(messages.length,1);assert.match(messages[0].subject,/business subscription inquiry/);assert.deepEqual({...env.DB.sqlite.prepare('SELECT status,attempts FROM outbox WHERE id=?').get('legacy-job')},{status:'pending',attempts:0});assert.equal(env.DB.sqlite.prepare('SELECT status FROM requests WHERE id=?').get('P1-legacy').status,'requested');});
