// Browser QA uses an in-memory API and fake transport only. No emails or bank transfers.
import {createRequire} from 'node:module';
import {mkdirSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {createDB} from '../server/local.mjs';
import {handleApi} from '../server/api.mjs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Windows/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
mkdirSync('qa',{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173',{waitUntil:'domcontentloaded'});
await page.locator('#service-mediation img').waitFor();
await page.evaluate(async()=>{await Promise.all(Array.from(document.images).map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=resolve;img.onerror=resolve;})));});
assert.equal(await page.locator('#services article').count(),6);
const rects=await page.locator('#services article').evaluateAll(els=>els.map(e=>({id:e.id,y:e.getBoundingClientRect().y,x:e.getBoundingClientRect().x})));
assert.equal(rects[0].y,rects[2].y);assert.equal(rects[3].y,rects[5].y);assert.ok(rects[3].y>rects[0].y);assert.equal(rects[3].id,'service-international');
await page.locator('#services').screenshot({path:'qa/services-desktop.png'});
await page.screenshot({path:'qa/home-desktop.png',fullPage:true});
// Fail-honest default is checked against the real unconfigured local backend.
const realConfig=await page.request.get('http://127.0.0.1:5173/api/config');assert.equal(realConfig.status(),200);
const now=new Date('2026-09-07T15:00:00Z');
await page.clock.install({time:now});
const env={DB:createDB(),NOW:()=>now,BOOKING_SECRET:'browser-secret-'.repeat(4),ADMIN_TOKEN:'browser-admin-'.repeat(4),RESEND_API_KEY:'fake-only',BOOKING_FROM_EMAIL:'sender@example.test',BOOKING_OWNER_EMAIL:'owner@example.test',ETRANSFER_EMAIL:'bank@example.test',MAIL_FETCH:async()=>new Response('{}',{status:200})};
await page.route('**/api/**',async route=>{const r=route.request();const result=await handleApi(new Request(r.url(),{method:r.method(),headers:r.headers(),...(r.method()==='GET'?{}:{body:r.postData()||'{}'})}),env);await route.fulfill({status:result.status,headers:Object.fromEntries(result.headers),body:await result.text()});});
await page.reload({waitUntil:'domcontentloaded'});
await page.locator('#service-drafting a').click();
assert.equal(await page.locator('#sb-serviceId').inputValue(),'drafting');
await page.locator('#sb-time').fill('15:00');
await page.getByRole('radio',{name:'Online',exact:true}).check();
await page.getByRole('radio',{name:'Zoom Call'}).check();
await page.getByRole('button',{name:'Continue',exact:true}).click();
await page.locator('#sb-operation').selectOption('draft-affidavit');
await page.locator('#sb-name').fill('Browser Test');
await page.locator('#sb-email').fill('browser@example.test');
await page.getByRole('button',{name:'Review request',exact:true}).click();
await page.getByText('$73.45',{exact:true}).waitFor();
await page.locator('.sb-consent input').check();
assert.equal(await page.getByText('$73.45',{exact:true}).count(),1,'Consent must not clear quote');
await page.locator('#smart-booking').screenshot({path:'qa/booking-review.png'});
await page.getByRole('button',{name:'Submit request',exact:true}).click();
await page.getByRole('heading',{name:'Request received'}).waitFor();
assert.equal(await page.getByText('bank@example.test',{exact:false}).count(),0);
const booking=env.DB.sqlite.prepare('SELECT id FROM requests').get();
const confirmation=await handleApi(new Request(`http://127.0.0.1:5173/api/admin/${booking.id}/confirm`,{method:'POST',headers:{Authorization:`Bearer ${env.ADMIN_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify({durationMinutes:30,externalCalendarChecked:true})}),env);
assert.equal(confirmation.status,200);
await page.getByRole('button',{name:'Check request status'}).click();
await page.getByRole('heading',{name:'Appointment confirmed'}).waitFor();
await page.getByText('Send to: bank@example.test',{exact:true}).waitFor();
await page.setViewportSize({width:390,height:844});
await page.locator('#service-mediation a').click();
await page.locator('#sb-time').fill('18:00');
assert.equal(await page.getByRole('radio',{name:'Mobile Visit',exact:true}).count(),0);
assert.equal(await page.getByRole('radio',{name:'In-Person',exact:true}).count(),0);
await page.getByRole('radio',{name:'Zoom Call'}).check();
await page.getByRole('button',{name:'Continue',exact:true}).click();
await page.locator('#sb-phone').fill('');
await page.getByRole('button',{name:'Review request',exact:true}).click();
await page.getByText('Enter your phone number.',{exact:true}).waitFor();
await page.locator('#smart-booking').screenshot({path:'qa/booking-mobile.png'});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'No mobile page overflow');
await page.locator('#services').screenshot({path:'qa/services-mobile.png'});
assert.deepEqual(errors,[]);
writeFileSync('qa/browser-results.json',JSON.stringify({passed:true,checks:['six original-order services','desktop 3+3','direct CTA preselection','draft option price','consent retains quote','submit then confirm then payment instructions','urgent online only','urgent Zoom phone required','mobile no overflow'],pageErrors:errors},null,2));
await browser.close();console.log('Browser checks passed. Screenshots saved in qa/. Test emails were intercepted.');
