import {useEffect,useRef,useState} from 'react';
import {SERVICES,OPERATIONS,MODES,allowedModes,localParts,urgentFor,money} from '../shared/catalog.mjs';
import './booking.css';
type Form = {serviceId:string;operation:string;date:string;time:string;mode:string;platform:string;quantity:number;hours:number;address:string;name:string;email:string;phone:string;notes:string;termsAccepted:boolean;termsVersion:string};
type Quote = {quoteToken?:string;status:string;lines:{label:string;amount:number;quantity:number;unit:string}[];reasons:string[];subtotal:number;tax:number;total:number;deposit:number;balance:number;billingUnit:string};
const initial:Form={serviceId:'',operation:'',...{date:localParts().date},time:'',mode:'',platform:'',quantity:1,hours:1,address:'',name:'',email:'',phone:'',notes:'',termsAccepted:false,termsVersion:''};
async function api(path:string,options:RequestInit={}){const r=await fetch(path,options);const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error||'Please try again.'),{fields:data.errors});return data;}
export function Summary({quote}:{quote:Quote|null}){
 if(!quote)return null;
 return <div className="sb-summary"><h4>{quote.status==='calculated'?'Price summary':'Known charges · review needed'}</h4>{quote.lines.map((x,i)=><div key={i}><span>{x.label}{x.quantity>1?` · ${x.quantity} ${x.unit}s`:''}</span><strong>{money(x.amount)}</strong></div>)}<div><span>Subtotal</span><span>{money(quote.subtotal)}</span></div><div><span>HST (13%)</span><span>{money(quote.tax)}</span></div><div className="sb-total"><span>{quote.status==='calculated'?'Total':'Known charges, including HST'}</span><strong>{money(quote.total)}</strong></div>{quote.status==='calculated'?<><div><span>50% deposit after confirmation</span><strong>{money(quote.deposit)}</strong></div><div><span>Remaining balance after deposit</span><span>{money(quote.balance)}</span></div></>:<p>No payment amount will be issued until the complete price is confirmed.</p>}{quote.reasons.map(x=><p key={x}>{x}</p>)}</div>;
}
export default function SmartBooking(){
 const [form,setForm]=useState<Form>(initial),[step,setStep]=useState(0),[errors,setErrors]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[quote,setQuote]=useState<Quote|null>(null),[settings,setSettings]=useState<{pageOperations:string[];termsVersion:string;terms:string}|null>(null),[result,setResult]=useState<any>(null),[record,setRecord]=useState<any>(null);
 const heading=useRef<HTMLHeadingElement>(null), requestKey=useRef(crypto.randomUUID()), stepStarted=useRef(false);
 useEffect(()=>{api('/api/config').then(s=>{setSettings(s);setForm(f=>({...f,termsVersion:s.termsVersion}));}).catch(()=>setMessage('Booking settings could not load. Retry the page or use our existing calendar.'));},[]);
 useEffect(()=>{const select=(event:Event)=>{const id=(event as CustomEvent).detail;const s=SERVICES.find(x=>x.id===id);if(!s)return;setForm(f=>({...f,serviceId:id,operation:s.operations.length===1?s.operations[0]:'',mode:'',platform:'',time:'',date:localParts().date,termsAccepted:false}));setStep(0);setQuote(null);setResult(null);setRecord(null);setErrors({});setMessage('');requestKey.current=crypto.randomUUID();};window.addEventListener('smart-booking',select);return()=>window.removeEventListener('smart-booking',select);},[]);
 useEffect(()=>{if(stepStarted.current)heading.current?.focus();stepStarted.current=true;},[step]);
 const set=(key:keyof Form,value:any)=>{setForm(f=>{const next={...f,[key]:value};if(['serviceId','time'].includes(key)){next.mode='';next.platform='';if(key==='serviceId'){const s=SERVICES.find(x=>x.id===value);next.operation=s?.operations.length===1?s.operations[0]:'';next.quantity=1;next.hours=1;}const modes=allowedModes(next.serviceId,next.time);if(next.time&&modes.length===1)next.mode=modes[0];}if(key==='mode'){next.platform='';if(value!=='mobile')next.address='';}return next;});if(key!=='termsAccepted')setQuote(null);setErrors(e=>({...e,[key]:''}));setMessage('');requestKey.current=crypto.randomUUID();};
 const service=SERVICES.find(x=>x.id===form.serviceId),op=OPERATIONS[form.operation as keyof typeof OPERATIONS],urgent=urgentFor(form.time),modes=allowedModes(form.serviceId,form.time);
 const err=(key:string)=>errors[key]?<span id={`err-${key}`} className="sb-field-error">{errors[key]}</span>:null;
 const props=(key:keyof Form)=>({id:`sb-${key}`,name:key,'aria-invalid':!!errors[key],'aria-describedby':errors[key]?`err-${key}`:undefined});
 const validateStep=()=>{
   const e:Record<string,string>={};
   if(step===0){if(!form.serviceId)e.serviceId='Choose a service.';if(!form.time)e.time='Choose a preferred time.';else if(form.date!==localParts().date||form.time<=localParts().time)e.time='Choose a future time today in Toronto.';else if(urgent){const t=localParts().time;const minutes=(v:string)=>Number(v.slice(0,2))*60+Number(v.slice(3));if(minutes(form.time)-minutes(t)<30)e.time='Urgent appointments need at least 30 minutes’ notice.';}if(!modes.includes(form.mode))e.mode='Choose an eligible format.';if(form.mode==='online'&&!form.platform)e.platform='Choose WhatsApp or Zoom.';}
   if(step===1){if(!form.operation)e.operation='Choose the document service.';if(form.mode==='online'&&op?.online===false)e.operation='This operation requires physical attendance. Change your time or format.';if(form.name.trim().length<2)e.name='Enter your full name.';if(!/^\S+@\S+\.\S+$/.test(form.email))e.email='Enter a valid email.';if((urgent||form.platform==='whatsapp')&&form.phone.replace(/\D/g,'').length<7)e.phone='Enter your phone number.';if(form.mode==='mobile'&&form.address.trim().length<8)e.address='Enter the service address.';}
   setErrors(e);if(Object.keys(e).length){setMessage('Please check the highlighted fields.');return false;}return true;
 };
 const next=async()=>{if(!validateStep())return;if(step===0){setStep(1);return;}setBusy(true);setMessage('');try{const q=await api('/api/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setQuote(q);setStep(2);}catch(e:any){setErrors(e.fields||{});setMessage(e.message);}finally{setBusy(false);}};
 const submit=async()=>{if(!form.termsAccepted){setErrors({termsAccepted:'Please acknowledge the booking request terms.'});return;}setBusy(true);setMessage('');try{const r=await api('/api/booking',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':requestKey.current},body:JSON.stringify({...form,quoteToken:quote?.quoteToken})});setResult(r);}catch(e:any){setErrors(e.fields||{});setMessage(e.message);if(e.fields)setStep(1);}finally{setBusy(false);}};
 const refresh=async()=>{setBusy(true);setMessage('');try{setRecord(await api(`/api/booking/${result.id}`,{headers:{'X-Booking-Access':result.access}}));}catch(e:any){setMessage(e.message);}finally{setBusy(false);}};
 if(result)return <div className="smart-booking"><p className="sb-eyebrow">Smart Booking</p><h3>{record?.status==='confirmed'?'Appointment confirmed':'Request received'}</h3><p>{record?.status==='confirmed'?'Your appointment time has been confirmed.':'We will review your requested time and contact you. Your appointment is not yet confirmed.'}</p><p className="sb-reference">Reference: {result.id}</p>{(record?.emailStatus||result.emailStatus)==='pending'&&<p role="status">Your request is saved, but our notification is delayed. Please contact us with your reference. Do not submit again.</p>}<p>{service?.title}<br/>{form.date} at {form.time} · Toronto<br/>{MODES[form.mode as keyof typeof MODES]} {form.platform}</p>{record?.quote&&<Summary quote={record.quote}/>} {record?.payment?<div className="sb-summary"><h4>Interac e-Transfer</h4><p>{record.paymentStatus==='received'?'Deposit received. Thank you.':`Deposit due: ${money(record.payment.amount)}`}</p><p>Send to: {record.payment.recipient}</p><p>Reference: {record.payment.reference}</p><p>Only mark a transfer complete in your bank after checking the recipient.</p></div>:<p>No payment is requested now. e-Transfer instructions are provided after booking confirmation.</p>}<button type="button" className="sb-primary" disabled={busy} onClick={refresh}>{busy?'Checking…':'Check request status'}</button>{message&&<p role="alert">{message}</p>}<p><a href="mailto:admin@on-callnotary.ca">Contact admin@on-callnotary.ca</a></p></div>;
 return <div className="smart-booking" id="smart-booking"><p className="sb-eyebrow">Smart Booking</p><h3 ref={heading} tabIndex={-1}>{['Choose your service & time','A few details','Review your request'][step]}</h3><p className="sb-intro">A short, three-step request. No payment until your booking is confirmed.</p><ol className="sb-steps" aria-label="Booking progress">{['Service & time','Details & contact','Review'].map((s,i)=><li key={s} aria-current={step===i?'step':undefined}><span>{i+1}</span>{s}</li>)}</ol>
 <form onSubmit={e=>{e.preventDefault();step===2?submit():next();}} noValidate>
 {message&&<div className="sb-error" role="alert">{message}</div>}
 {step===0&&<>
 <label htmlFor="sb-serviceId">Service type *</label><select {...props('serviceId')} value={form.serviceId} onChange={e=>set('serviceId',e.target.value)}><option value="">Choose a service</option>{SERVICES.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select>{err('serviceId')}
 {form.serviceId&&<><label htmlFor="sb-time">Preferred time today *</label><p className="sb-help">{form.date} · America/Toronto. Requested times are subject to confirmation.</p><input {...props('time')} type="time" value={form.time} onChange={e=>set('time',e.target.value)}/>{err('time')}<p className="sb-help">Before 6 PM: eligible in-person, online or mobile services. From 6 PM: online urgent requests only, at least 30 minutes ahead.</p><a className="sb-help" href="mailto:admin@on-callnotary.ca?subject=Future%20appointment%20request">Need another date? Contact us.</a></>}
 {form.time&&form.serviceId&&<><fieldset><legend>Appointment format *</legend><div className="sb-options">{modes.map(mode=><label key={mode} className={form.mode===mode?'selected':''}><input type="radio" name="mode" value={mode} checked={form.mode===mode} onChange={()=>set('mode',mode)}/>{MODES[mode as keyof typeof MODES]}</label>)}</div>{!modes.length&&<p>This service requires physical attendance and cannot be booked after 6 PM. Choose an earlier time.</p>}</fieldset>{err('mode')}{urgent&&<p className="sb-help">Urgent pricing is double the regular price for eligible commissioning. Other service eligibility requires review.</p>}</>}
 {form.mode==='online'&&<><fieldset><legend>Video platform *</legend><div className="sb-options">{[['whatsapp','WhatsApp Video Call'],['zoom','Zoom Call']].map(([v,l])=><label key={v} className={form.platform===v?'selected':''}><input type="radio" name="platform" checked={form.platform===v} onChange={()=>set('platform',v)}/>{l}</label>)}</div></fieldset>{err('platform')}</>}
 </>}
 {step===1&&<>
 <p className="sb-help">{service?.title} · {form.time} · {MODES[form.mode as keyof typeof MODES]}</p>
 {service&&service.operations.length>1&&<><label htmlFor="sb-operation">{form.serviceId==='drafting'?'Document to draft':'Service needed'} *</label><select {...props('operation')} value={form.operation} onChange={e=>set('operation',e.target.value)}><option value="">Choose an option</option>{service.operations.map(id=><option key={id} value={id}>{OPERATIONS[id as keyof typeof OPERATIONS].label}</option>)}</select></>}{err('operation')}
 {op?.unit==='seal'&&<><label htmlFor="sb-quantity">Number of {settings?.pageOperations.includes(form.operation)?'pages':'seals'} *</label><input {...props('quantity')} type="number" min="1" max="500" value={form.quantity} onChange={e=>set('quantity',Number(e.target.value))}/>{err('quantity')}<p className="sb-help">{settings?.pageOperations.includes(form.operation)?'1–14 pages: $15/page; 15–49: $4/page; 50+: $3/page.':'Existing seal rates apply. Ask us to review bulk page pricing separately.'}</p></>}
 {form.operation==='mediation'&&<><label htmlFor="sb-hours">Planned hours *</label><input {...props('hours')} type="number" min="1" max="8" step="1" value={form.hours} onChange={e=>set('hours',Number(e.target.value))}/>{err('hours')}<p className="sb-help">$100/hour. For a different duration, add a note. Any overtime arrangement must be agreed separately.</p></>}
 {form.serviceId==='drafting'&&<p className="sb-help">Affidavit $65 · Travel Consent Letter $50. Commissioning and notarization are separate services.</p>}
 {form.mode==='mobile'&&<><label htmlFor="sb-address">Service address *</label><input {...props('address')} autoComplete="street-address" value={form.address} onChange={e=>set('address',e.target.value)}/>{err('address')}<p className="sb-help">$1.50/km; the billable distance is confirmed with your quote.</p></>}
 <label htmlFor="sb-name">Full name *</label><input {...props('name')} autoComplete="name" value={form.name} onChange={e=>set('name',e.target.value)}/>{err('name')}
 <label htmlFor="sb-email">Email address *</label><input {...props('email')} type="email" autoComplete="email" value={form.email} onChange={e=>set('email',e.target.value)}/>{err('email')}
 <label htmlFor="sb-phone">Phone number {urgent||form.platform==='whatsapp'?'*':'(optional)'}</label><input {...props('phone')} type="tel" autoComplete="tel" value={form.phone} onChange={e=>set('phone',e.target.value)}/>{err('phone')}
 <details className="sb-notes"><summary>Add a note (optional)</summary><label htmlFor="sb-notes">Additional details</label><textarea {...props('notes')} maxLength={2000} value={form.notes} onChange={e=>set('notes',e.target.value)}/></details>
 </>}
 {step===2&&<><p><strong>{service?.title}</strong><br/>{op?.label}<br/>{form.date} · {form.time} America/Toronto<br/>{MODES[form.mode as keyof typeof MODES]} {form.platform}{form.address&&<><br/>{form.address}</>}<br/>{form.name} · {form.email}</p><Summary quote={quote}/><p className="sb-help">This is a request, not a confirmed appointment. We will confirm availability and any price requiring review. e-Transfer instructions follow confirmation.</p>{settings?.terms&&<p className="sb-help">{settings.terms}</p>}<label className="sb-consent"><input type="checkbox" checked={form.termsAccepted} onChange={e=>set('termsAccepted',e.target.checked)}/>I understand that availability and final scope require confirmation, and payment is requested only after confirmation.{settings?.terms?' I accept the terms above.':''}</label>{err('termsAccepted')}</>}
 <div className="sb-actions">{step>0&&<button type="button" disabled={busy} onClick={()=>{setStep(step-1);setMessage('');}}>Back</button>}<button className="sb-primary" type="submit" disabled={busy||!settings}>{busy?'Please wait…':step===2?'Submit request':step===1?'Review request':'Continue'}</button></div>
 </form></div>;
}
